#!/bin/csh -f
#PBS -r y                                                              #This job is restartable
#PBS -j oe                                                             #STDOUT and STDERR are in the same file, specified below in the '-o' option
#PBS -q batch                                                          #Do not change this - it tells your job where to run
#PBS -S /bin/sh                                                        #Do not change this - it keeps your job from issuing a false alarm
#PBS -E                                                                #Do not change this - it gives your job more and more useful Moab environment variables
#PBS -N  Bergs_Empty_Run                                               #Job Name:             You may want to change this to reflect your job's purpose or relation to an experiment
#PBS -l partition=c3
#PBS -l size=4                                                        #You will need to change this to reflect your job's core requirements - 24 is the current core increment.
#PBS -l walltime=16:00:00                                              #You MUST change this to reflect your job's expected run time, including copy time
#PBS -m bea                                                            #Email options: You may want to change this to reduce your incoming email stream

######################################################################################################################
#
#  Gaea c1ms batch skeleton version 0.9
#  
#  0.9 - Initial version - 20110906 - Daniel Gall - Daniel.Gall@noaa.gov
#
######################################################################################################################

#Source the system initialization scripts (but not the user's so as to avoid interactive settings that can poison us)
source /etc/csh.cshrc

#Run the experiment
aprun -n 128 ../../../../../build/intel/ice_ocean_SIS2/repro/MOM6
